### ISSUE TITLE
"If you installed via Marketplace, the color scheme can be changed directly in the theme options." - Location?

### ISSUE THREAD

**Issue by Chriskey23** [sanoojes/spicetify-colorful#1]
Hi, could you please explain where to change the theme settings, when the theme is installed through spicetify marketplace?
I Can't find it in the spicetify/spotify client.

**Comment by sanoojes** [comment]
you need to click the user avatar on top with will open a menu with better bloom settings option just select it and change settings
https://discord.com/channels/1242343326175330396/1245652053867630703/1249014853935431731

i will add them in the readme after v2 release

**Comment by sanoojes** [comment]
![image](https://github.com/sanoojes/spicetify-colorful/assets/93819264/a6ae5e00-7d78-4e06-8247-91b6c4d62acf)
here it will show better bloom settings for you

**Comment by sanoojes** [comment]
there is no built in theme settings if you are looking to change the colors you can do it by editing the config file `config-xpui.ini` 
run this to open the folder`spicetify config-dir`

**Comment by Chriskey23** [comment]
Alright thank you very much for your quick reply. I was a bit confused, because this is in your description:
![image](https://github.com/sanoojes/spicetify-colorful/assets/55251115/7c9b68b1-b0a1-452e-a811-2c801a6761a8)

**Comment by sanoojes** [comment]
> Alright thank you very much for your quick reply. I was a bit confused, because this is in your description: ![image](https://private-user-images.githubusercontent.com/55251115/341768106-7c9b68b1-b0a1-452e-a811-2c801a6761a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjE4NjgsIm5iZiI6MTcxOTA2MTU2OCwicGF0aCI6Ii81NTI1MTExNS8zNDE3NjgxMDYtN2M5YjY4YjEtYjBhMS00NTJlLWE4MTEtMmM4MDFhNjc2MWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEzMDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5Y2IzOTRmODc1OWIwNDFlN2NlY2FmNjdjOGJjODRmMWZhOGFkNjY4M2ZhOTA0ZTQ0MTJjMzRlYTE2ZDMyNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.24p0r24cJloeen9UVEIqI3omdRWve7GeiBsOpdoe-jE)

ohh soory it was ai gen

**Comment by Yu21666** [comment]
![Capture d'écran 2024-06-24 013003](https://github.com/sanoojes/spicetify-colorful/assets/173640707/0cb9422c-dc14-4cb4-af28-f00440f79ce9)

you can choose in this menu
